apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
spec:
  type:  {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.labelName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort:  {{ .Values.frontend.service.nodePort }}
